name: Continuous Integration

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        track:
          - c
          - cpp
          - csharp
          - elixir
          - fsharp
          - go
          - java
          - javascript
          - python
          - ruby
          - rust
          - swift
        exercises:
          - concept
          - practice
        exclude:
          - track: c
            exercises: concept
          - track: rust
            exercises: concept
    runs-on: ubuntu-22.04
    steps:
      - name: Check out exercism/${{ matrix.track }}
        uses: actions/checkout@v4
        with:
          repository: exercism/${{ matrix.track }}
          ref: main
      - name: Check out current repository
        uses: actions/checkout@v4
        with:
          path: .github/actions/test-runner
      - name: Run Action
        uses: ./.github/actions/test-runner
        with:
          test-runner-image: exercism/${{ matrix.track }}-test-runner
          test-concept-exercises: ${{ matrix.exercises == 'concept' }}
          test-practice-exercises: ${{ matrix.exercises == 'practice' }}
